[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-get-native-call-capabilities",
    "allow-connect-native-call",
    "allow-disconnect-native-call",
    "allow-set-native-call-microphone-enabled",
    "allow-set-native-call-camera-enabled",
    "allow-set-native-call-screen-share-enabled",
    "allow-set-native-call-pip-enabled",
    "allow-switch-native-call-camera",
    "allow-set-native-call-remote-video-overlay",
    "allow-clear-native-call-remote-video-overlay",
    "allow-set-native-call-local-video-overlay",
    "allow-clear-native-call-local-video-overlay",
    "allow-start-system-call",
    "allow-end-system-call",
    "allow-set-system-call-muted",
    "allow-drain-pending-system-call-actions",
    "allow-fulfill-answer-call",
    "allow-fulfill-end-call",
    "allow-report-system-call-connected",
    "allow-set-native-call-encryption-key",
    "allow-get-native-call-state",
    "allow-get-audio-routes",
    "allow-set-audio-route",
    "allow-update-call-display",
]
