[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-getNativeCallCapabilities",
    "allow-connectNativeCall",
    "allow-disconnectNativeCall",
    "allow-setNativeCallMicrophoneEnabled",
    "allow-setNativeCallCameraEnabled",
    "allow-setNativeCallScreenShareEnabled",
    "allow-setNativeCallPiPEnabled",
    "allow-switchNativeCallCamera",
    "allow-setNativeCallRemoteVideoOverlay",
    "allow-clearNativeCallRemoteVideoOverlay",
    "allow-setNativeCallLocalVideoOverlay",
    "allow-clearNativeCallLocalVideoOverlay",
    "allow-reportSystemIncomingCall",
    "allow-startSystemCall",
    "allow-answerSystemCall",
    "allow-endSystemCall",
    "allow-setSystemCallMuted",
    "allow-drainPendingSystemCallActions",
    "allow-fulfillAnswerCall",
    "allow-fulfillEndCall",
    "allow-reportSystemCallConnected",
    "allow-setNativeCallEncryptionKey",
    "allow-getNativeCallState",
    "allow-getAudioRoutes",
    "allow-setAudioRoute",
    "allow-sendDTMF",
    "allow-updateCallDisplay",
    "allow-reportSystemCallAnsweredElsewhere",
    "allow-reportSystemCallDeclinedElsewhere",
    "allow-reportSystemCallUnanswered",
    "allow-declineSystemCall",
]
